version: "3.4"

networks:
  cb:
    driver: bridge

volumes:
  prometheus_data: {}

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./.prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    links:
      - challenge-bypass:challenge-bypass
    depends_on:
      - challenge-bypass
    networks:
      - cb
    restart: always

  postgres:
    container_name: postgres
    image: postgres:10.4
    environment:
      - "POSTGRES_USER=btokens"
      - "POSTGRES_PASSWORD=password"
    networks:
      - cb
  challenge-bypass:
    container_name: challenge-bypass
    image: challenge-bypass-builder 
    restart: always
    build:
      context: .
      target: go_builder 
    ports:
      - "2416:2416"
    environment:
      - "SENTRY_DSN"
      - "DATABASE_URL=postgres://btokens:password@postgres/btokens?sslmode=disable"
    depends_on:
      - postgres
    networks:
      - cb

